version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    networks:
      - softy-pinko-network

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    networks:
      - softy-pinko-network

proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"  # Map proxy port 80 to host port 80
    depends_on:
      - back-end
      - front-end
    networks:
      - softy-pinko-network


networks:
  softy-pinko-network:
    driver: bridge
